name: Deploy table

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT: ${{ secrets.SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_USER: ${{ secrets.SNOWFLAKE_CONNECTIONS_DEFAULT_USER }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_PASSWORD: ${{ secrets.SNOWFLAKE_CONNECTIONS_DEFAULT_PASSWORD }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_DB: ${{ secrets.SF_DATABASE }}
      SNOWFLAKE_CONNECTIONS_DEFAULT_WH: ${{ secrets.SF_WH }}
      REPO_NAME: ${GITHUB_REPOSITORY

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install snowflake-cli
        uses: Snowflake-Labs/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"
          default-config-file-path: 'config.toml'

      
      - name: Deploy scripts to preprod environment
        run: echo $repo_name
